dist: xenial

language: python

cache: pip


matrix:
  include:
    - env: TOXENV=lint
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.8
      env: TOXENV=py38
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - env: TOXENV=docker-test
    - env: TOXENV=docs

#matrix:
#  allow_failures:
#    - python: '3.8-dev'

services:
  - docker

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -v
