dist: xenial

language: python

cache: pip

env:
  - TOX_PARALLEL_NO_SPINNER=1

python:
  - 'pypy3'
  - '3.8'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'

#matrix:
#  allow_failures:
#    - python: '3.8-dev'

services:
  - docker

install:
  - pip install tox-travis

script:
  - tox -p auto

after_success:
  - pip install codecov
  - codecov -v
