dist: xenial

language: python

cache: pip


matrix:
  include:
    - env: TOXENV=lint
    - python: pypy3
    - python: 3.8
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - env: TOXENV=docker-tests
    - env: TOXENV=docs

#matrix:
#  allow_failures:
#    - python: '3.8-dev'

services:
  - docker

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -v
