name: prepare-release
on:
  push:
    branch: [ 'release/*' ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Prepare the release
      id: update
      run: |
        ./scripts/prepare_release.sh ${{ steps.get_version.outputs.VERSION }}
    
    - name: Print output
      run: echo ${{ steps.update.outputs.version_updated}}

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v2.7.0
      with:
        branch: ${{ steps.get_version.outputs.VERSION }}
        title: '[pre-release] Update changelogs, version [${{ steps.get_version.outputs.VERSION }}]'
        # team-reviewers: TODO: set this
      if: ${{ steps.update.outputs.version_updated == 1 }}
